on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ftp-quaiantiquetesttom.alwaysdata.net
        username: quaiantiquetesttom
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        server-dir: /www/
        exclude: | 
          **/.git*
          **/.git*/**
          **/node_modules/bootstrap/scss/**
          **/node_modules/bootstrap/js/**
          **/node_modules/bootstrap-icons/icons/**
